#!/bin/bash

# Sanitizers link with -allow-shlib-undefined which can sometimes cover up
# CMake errors on my part, it is good to run this to make sure it links
# cleanly and all dependencies are properly defined.

export CFLAGS="-O0"

source limits.sh

cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS=libc          \
    -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_TESTS=ON     \
    -DLLVM_TARGETS_TO_BUILD=X86 -DBUILD_SHARED_LIBS=On      \
    -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang   \
    $limits $other
