#!/bin/bash

# This is my primary debug configuration when developing.

source platform.sh

export CFLAGS="-O0 -g -fno-omit-frame-pointer"

source limits.sh

cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS=libc          \
    -DLLVM_USE_SANITIZER='Address;Undefined'                \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                      \
    -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Debug    \
    -DLLVM_USE_SPLIT_DWARF=ON -DLLVM_BUILD_TESTS=ON         \
    -DLLVM_ENABLE_ASSERTIONS=ON -DBUILD_SHARED_LIBS=On      \
    -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang   \
    $limits $other                                          \
